### ISSUE TITLE
Allow lsp to read my projects automatically

### ISSUE THREAD

**Issue by blessedbythestorm** [Eliah-Lakhin/ad-astra#2]
Would it be possible to bundle and pass several libarary exports to the lsp for completions?

I have:

1 core lib crate -> exports core functionality.
1 glue lib crate -> imports core lib and exports additional functionality and declares the export package.
1 user bin crate -> imports glue lib and exports user defined functionality.

I want the lsp to have completions for exported members of all of those together (or maybe as separate packages). Your documentation mentions there should only be a single package?

Is there currently a setup to allow anything like that?
I use Helix as an editor at the moment and I've managed to compile your lsp server example and link it to it. I've made a custom tree-sitter grammar and highlights.scm for syntax highlighting and all of that works fine. But I cant manage to get the combined completions. Only those defined directly in the lsp executable are shown. 

As a test I've included the glue lib with the lsp to try and export an engine function with it. 

I've done:

```rust
// lib.rs

#[export(package)]
#[derive(Default)]
pub struct Package;

#[export]
pub fn hello_script() {
    println!("Hello!");
}

// lsp main.rs:
use titan::Package;

#[export]
pub fn dbg(x: DynamicArgument<DynamicType>) -> DynamicReturn<DynamicType> {
    let message = x.data.stringify(false);
    let tooltip = x.data.stringify(true);

    // debug!("{}", tooltip);

    let tooltip = match message == tooltip {
        true => String::new(),
        false => format!("```\n{tooltip}\n```"),
    };

    inlay_hint(x.origin, message, tooltip);

    DynamicReturn::new(x.data)
}

fn main() {
    let server_config = LspServerConfig::new();

    let mut logger_config = LspLoggerConfig::new();

    let transport_config = LspTransportConfig::Stdio;

    logger_config.server = LspLoggerServerConfig::Off;

    LspServer::startup(
        server_config,
        logger_config,
        transport_config,
        Package::meta(),
    );
}

```

I get the following errors from the lsp when attempting this:

```
2024-10-06T02:25:07.764 helix_lsp::transport [ERROR] adastra-lsp err <- "thread '[file:///home/stormblessed/dev/titan/titan-viewer/content/test_script.adastra] (diagnostics 3)' panicked at titan-lsp/src/main.rs:16:8:\n"
2024-10-06T02:25:07.764 helix_lsp::transport [ERROR] adastra-lsp err <- "Package titan-lsp@0.1.0 is not registered.\n"
2024-10-06T02:25:07.764 helix_lsp::transport [ERROR] adastra-lsp err <- "note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n"
2024-10-06T02:25:07.764 helix_lsp::transport [ERROR] adastra-lsp err <- "thread '[file:///home/stormblessed/dev/titan/titan-viewer/content/test_script.adastra] (diagnostics 2)' panicked at titan-lsp/src/main.rs:16:8:\n"
2024-10-06T02:25:07.764 helix_lsp::transport [ERROR] adastra-lsp err <- "Package titan-lsp@0.1.0 is not registered.\n"
2024-10-06T02:25:12.725 helix_lsp::transport [ERROR] adastra-lsp err <- "thread '[file:///home/stormblessed/dev/titan/titan-viewer/content/test_script.adastra] (send completion)' panicked at titan-lsp/src/main.rs:16:8:\n"
2024-10-06T02:25:12.725 helix_lsp::transport [ERROR] adastra-lsp err <- "Package titan-lsp@0.1.0 is not registered.\n"
```
Is there a way to combine the packages for the lsp? I think a better solution would perhaps be to generate export data into an intermediate directory that then can get read from a globally installed lsp. 

Thanks and sorry if I missed anything.

**Comment by blessedbythestorm** [comment]
Sorry, seems I preemptively asked the question. I figured out your docs say it should be a package per crate and it does work like that!

I guess my question now steers towards allowing my libs users to export functionality without having to recompile the lsp. Have you got any plans for a globally installed lsp that can do this?

Thanks and sorry for bothering!

**Comment by Eliah-Lakhin** [comment]
@blessedbythestorm Thank you for your feedback! I'm glad to hear that Ad Astra LSP works well with Helix.

Regarding your question, I do plan to implement hot updating features, including LSP hot patching. These features were part of the original vision, but I decided to delay them for future versions. The solution might involve a middleware LSP server that delegates the actual analysis to child semantic analysis servers, possibly running in separate processes. Alternatively, it could involve patching the already running LSP server.

Both approaches raise important questions about semantic metadata isolation, versioning, and the efficiency of hot reloading, all of which need to be addressed first. Realistically, it will take some time before these features can be released, but they are definitely on my roadmap.

**Comment by blessedbythestorm** [comment]
Thanks for the response! I'll adapt my solution for the time being then.
